import 'server-only'

import { google } from 'googleapis'
import { startOfWeek, endOfWeek, addWeeks, format } from 'date-fns'
import type { DashboardCalendarEvent, WeekRange } from '@/lib/types/calendar'

function getGoogleAuth() {
  const credentials = JSON.parse(process.env.GOOGLE_SERVICE_ACCOUNT_KEY!)
  return new google.auth.GoogleAuth({
    credentials,
    scopes: [
      'https://www.googleapis.com/auth/calendar.readonly',
      'https://www.googleapis.com/auth/spreadsheets.readonly',
    ],
  })
}

function parseLocalParts(isoString: string) {
  const tIdx = isoString.indexOf('T')
  if (tIdx === -1) {
    const [year, month, day] = isoString.split('-').map(Number)
    return { year, month: month - 1, day, hours: 0, minutes: 0, allDay: true }
  }
  const [year, month, day] = isoString.substring(0, tIdx).split('-').map(Number)
  const hours   = parseInt(isoString.substring(tIdx + 1, tIdx + 3), 10)
  const minutes = parseInt(isoString.substring(tIdx + 4, tIdx + 6), 10)
  return { year, month: month - 1, day, hours, minutes, allDay: false }
}

function julianDay(y: number, m: number, d: number) {
  return Math.floor(y * 365.25) + Math.floor((m + 1) * 30.6) + d
}

// Parse a time string like "7:30 AM" or "3:00 PM" into minutes-from-midnight
function parseTimeStr(timeStr: string): number {
  if (!timeStr) return 0
  const m = timeStr.trim().match(/^(\d{1,2}):?(\d{0,2})\s*(AM|PM)?$/i)
  if (!m) return 0
  let hours = parseInt(m[1], 10)
  const minutes = m[2] ? parseInt(m[2], 10) : 0
  const period = (m[3] ?? '').toUpperCase()
  if (period === 'PM' && hours < 12) hours += 12
  if (period === 'AM' && hours === 12) hours = 0
  return hours * 60 + minutes
}

// Read saved Sunday-Plan AdminState for a given week (YYYY-MM-DD Sunday).
// Returns null if no saved state for that week.
async function fetchAdminState(weekStart: string): Promise<any | null> {
  const auth = getGoogleAuth()
  const sheets = google.sheets({ version: 'v4', auth })
  const sheetsId = process.env.GOOGLE_SHEETS_ID!

  try {
    const res = await sheets.spreadsheets.values.get({
      spreadsheetId: sheetsId,
      range: 'AdminState!A2:C200',
    })
    const rows = (res.data.values ?? []) as string[][]
    const matching = rows
      .filter(r => r[0] === weekStart)
      .sort((a, b) => (b[1] ?? '').localeCompare(a[1] ?? ''))
    if (matching.length === 0) return null
    return JSON.parse(matching[0][2])
  } catch (err) {
    console.warn('AdminState fetch failed:', err)
    return null
  }
}

// Convert a saved Sunday-Plan event (CalendarEvent type from src/lib/types.ts)
// into a DashboardCalendarEvent. Used for school events generated by Sunday Plan.
function savedEventToDashboard(saved: any, weekStartDate: Date): DashboardCalendarEvent | null {
  if (saved.dayIdx === undefined || saved.dayIdx < 0 || saved.dayIdx > 6) return null

  const eventDate = new Date(weekStartDate)
  eventDate.setDate(eventDate.getDate() + saved.dayIdx)
  const dateStr = eventDate.toISOString().slice(0, 10)

  // Saved has time string like "7:30 AM" or "4:00–6:00 PM"
  // For simple time strings we treat as start, default duration 30 min for school, 1h otherwise
  let startMinutes = 0
  let endMinutes = 60
  const isSchool = typeof saved.id === 'string' && saved.id.startsWith('school_')

  if (saved.allDay) {
    startMinutes = 0
    endMinutes = 24 * 60
  } else if (saved.time) {
    const range = saved.time.match(/^(.+?)[–\-](.+)$/)
    if (range) {
      // Range form like "4:00–6:00 PM" — apply trailing AM/PM to start if missing
      let startStr = range[1].trim()
      const endStr = range[2].trim()
      const endPeriod = (endStr.match(/(AM|PM)/i) ?? [])[1]
      if (endPeriod && !/AM|PM/i.test(startStr)) startStr = `${startStr} ${endPeriod}`
      startMinutes = parseTimeStr(startStr)
      endMinutes = parseTimeStr(endStr)
    } else {
      startMinutes = parseTimeStr(saved.time)
      endMinutes = startMinutes + (isSchool ? 30 : 60)
    }
  } else {
    // No time → treat all-day
    startMinutes = 0
    endMinutes = 24 * 60
  }

  return {
    id: saved.id ?? `synth-${saved.dayIdx}-${saved.title}`,
    title: saved.title ?? '(untitled)',
    startISO: `${dateStr}T${String(Math.floor(startMinutes/60)).padStart(2,'0')}:${String(startMinutes%60).padStart(2,'0')}:00`,
    endISO:   `${dateStr}T${String(Math.floor(endMinutes/60)).padStart(2,'0')}:${String(endMinutes%60).padStart(2,'0')}:00`,
    allDay: !!saved.allDay,
    location: saved.location ?? undefined,
    dayIdx: saved.dayIdx,
    startMinutes,
    endMinutes,
    involvedIds: saved.involvedIds ?? [],
    driverId: saved.driverId ?? null,
    transportStatus: saved.transportStatus ?? 'unset',
    isSchoolEvent: isSchool,
  }
}

// Patterns that indicate an event is a school drop-off / pick-up, used to
// avoid double-counting when both Google Calendar AND saved state contain it
function isSchoolish(title: string, id?: string) {
  if (id?.startsWith('school_')) return true
  const lower = title.toLowerCase()
  return lower.includes('school drop') || lower.includes('school pick')
}

export async function fetchWeekCalendar(weekOffset: number = 0): Promise<WeekRange> {
  const calendarId = process.env.GOOGLE_CALENDAR_ID ?? 'primary'
  const referenceDate = addWeeks(new Date(), weekOffset)
  const weekStart = startOfWeek(referenceDate, { weekStartsOn: 0 })
  const weekEnd   = endOfWeek(referenceDate,   { weekStartsOn: 0 })
  const weekStartStr = format(weekStart, 'yyyy-MM-dd')

  const auth = getGoogleAuth()
  const calendar = google.calendar({ version: 'v3', auth })

  const response = await calendar.events.list({
    calendarId,
    timeMin: weekStart.toISOString(),
    timeMax: weekEnd.toISOString(),
    singleEvents: true,
    orderBy: 'startTime',
    maxResults: 250,
  })

  const wsParts = {
    year: weekStart.getFullYear(),
    month: weekStart.getMonth(),
    day: weekStart.getDate(),
  }
  const wsJulian = julianDay(wsParts.year, wsParts.month, wsParts.day)

  // Fetch saved Sunday-Plan state for this week (may be null)
  const adminState = await fetchAdminState(weekStartStr)
  const savedEvents: any[] = adminState?.events ?? []

  // ─── Calendar events: merge saved metadata, drop school-ish ones ───
  const calendarEvents: DashboardCalendarEvent[] = (response.data.items ?? [])
    .map(raw => {
      const startStr = raw.start?.dateTime ?? raw.start?.date
      const endStr   = raw.end?.dateTime   ?? raw.end?.date
      if (!startStr || !raw.id) return null
      // Skip school-ish events from Google Calendar — we get them from saved state
      if (isSchoolish(raw.summary ?? '', raw.id)) return null

      const startParts = parseLocalParts(startStr)
      const endParts   = endStr ? parseLocalParts(endStr) : startParts

      const startJulian = julianDay(startParts.year, startParts.month, startParts.day)
      const dayIdx = startJulian - wsJulian
      if (dayIdx < 0 || dayIdx > 6) return null

      const startMinutes = startParts.allDay ? 0 : startParts.hours * 60 + startParts.minutes
      const sameDay = startParts.year === endParts.year &&
                      startParts.month === endParts.month &&
                      startParts.day === endParts.day
      const endMinutes = startParts.allDay
        ? 24 * 60
        : sameDay ? endParts.hours * 60 + endParts.minutes : 24 * 60

      const evt: DashboardCalendarEvent = {
        id: raw.id,
        title: raw.summary ?? '(untitled)',
        startISO: startStr,
        endISO: endStr ?? startStr,
        allDay: startParts.allDay,
        location: raw.location ?? undefined,
        description: raw.description ?? undefined,
        dayIdx,
        startMinutes,
        endMinutes,
        involvedIds: [],
        driverId: null,
        transportStatus: 'unset',
        isSchoolEvent: false,
      }

      // Merge saved metadata if Sunday Plan tagged this event
      const saved = savedEvents.find((s: any) => s.id === raw.id)
                ?? savedEvents.find((s: any) =>
                     s.title === raw.summary && s.dayIdx === dayIdx)
      if (saved) {
        evt.involvedIds = saved.involvedIds ?? []
        evt.driverId = saved.driverId ?? null
        evt.transportStatus = saved.transportStatus ?? 'unset'
      }

      return evt
    })
    .filter((e): e is DashboardCalendarEvent => e !== null)

  // ─── School events: pull straight from saved state ───
  const schoolEvents: DashboardCalendarEvent[] = savedEvents
    .filter((s: any) => typeof s.id === 'string' && s.id.startsWith('school_'))
    .map(s => savedEventToDashboard(s, weekStart))
    .filter((e): e is DashboardCalendarEvent => e !== null)

  const all = [...calendarEvents, ...schoolEvents]
    .sort((a, b) => a.dayIdx !== b.dayIdx ? a.dayIdx - b.dayIdx : a.startMinutes - b.startMinutes)

  return {
    weekStart: weekStartStr,
    weekEnd:   format(weekEnd, 'yyyy-MM-dd'),
    events: all,
    syncedAt: new Date().toISOString(),
  }
}
